# Introduction to Numpy

Many of the examples used in this notebook were taken from: https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html

The Ultimate Beginner's Guide to NumPy: https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54

These websites can be visite before, during or after working with this notebook and will help to explain and reinforce the important concepts related to NumPy.



# Modules and Packages

Much of the functionality and versatility of Python comes in the form of modules (collections of classes and methods) that you can import.

If someone saves a text file with Python code in it and gives it the ".py" file extension, you can run that file in your own session using the **import** statement. If that file contained functions or new classes, then we get to use them!
  - A **Module** is one Python file.
  - A **Package** is a collection of Python files.
  


In [1]:
import math
import numpy
print(math.sqrt)
print(numpy.sqrt)

<built-in function sqrt>
<ufunc 'sqrt'>


In [2]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [3]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

# Numpy

NumPy is a Python package that stands for "Numerical Python".  It is a library that makes heavy use of multidimensional array objects and contains a set of routines for processing arrays. 

Using NumPy, you can perform these types of operations:
    - Mathematical and logical operations on arrays.
    - Fourier transforms and routines for shape manipulation.
    - Operations related to linear algebra. NumPy has in-built functions for linear 
      algebra and random number generation (that you used for generating fractals)
      
NumPy is a package for creating, transforming, and calculation with Arrays and Matrices. **It is the most essential package of the entire Python scientific library.**

The more familiar you are with NumPy, the more effective you will be during data analysis.

## Numpy as a Matlab replacement

NumPy is typically used with other packages, like SciPy (Scientific Python) and Matplotlib. This combination is widely used as a free replacement for Matlab, a popular programming language, especially in the Neuroscience community.  Since Python is a general programming language, it has more flexibility compared to Matlab.  

For anyone who has used Matlab in the past or is interested in learning more details about their similiarities and differences, you will find this page very informative:

https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

## The "Import" Statement, Dot Notation, and Namespaces
To keep from overwriting other functions that may have the same name, Python lets us use the Dot to tell it which packages' function we want to use.  What comes before the dot (or whether a dot is even needed) is referred to as an object's **Namespace**.

## "From" lets you bring modules and functions into other namespaces. 

In [4]:
from math import sqrt
# from numpy import sqrt
sqrt

<function math.sqrt(x, /)>

# Bring all the function definitions into the main name space with *

In [5]:
from numpy import *
# from math import *
sin?

Different modules might define functions with the same name, and then these might conflict. For instance, both the math and the numpy module define a function called sin()

**Warning:** When importing all functions like this, functions will be overwritten in the namespace and only the most recently imported function will be active.

It is usually best to assign a very short alias to avoid any possible confusion!

## Preferred Method for Importing: The "as" operater lets you assign a different variable name in the import statement

If numpy is too long to write every time, we can use the alias 

In [6]:
import math as m
import numpy as np

## Import Submodules with the Dot notation and "as"

In [7]:
import numpy.linalg as linalg
import numpy.random as rdm

In [8]:
rdm # press Tab after the dot (.) and start typing to see possible inputs.

<module 'numpy.random' from '/home/dustin/anaconda3/lib/python3.7/site-packages/numpy/random/__init__.py'>

In [9]:
a = 10 - 5*rdm.random(2); print(a)

[5.76659681 5.46009922]


In [10]:
# Get help with a question mark before or after the function. Uncomment each line individually:

# help(rdm.random)
# ?rdm.random
# rdm.random?

# Return random floats in the half-open interval [0.0, 1.0)

In [11]:
np.sin(a)

array([-0.49391669, -0.73324774])

a is a list, and becomes a numpy array when it is passed to the sin function.

In [12]:
m.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

Numpy is advantageous because it performs operations directly on arrays, unlike math

## NumPy Array Objects

To construct a **numpy.array**, you should give it an **Iterable**.  It will guess what data type you want, but this can be set with the **dtype** **keyword argument**:

In [13]:
a_array = np.array([1, 2, 3, 4])
a_array # But do we want integers?

array([1, 2, 3, 4])

In [14]:
a_float_array = np.array([1, 2, 3, 4], dtype=float)
a_float_array

array([1., 2., 3., 4.])

In [15]:
list1 = ['a', 1, 3.14, 5+2j]
list1

['a', 1, 3.14, (5+2j)]

In [16]:
np.array(list1)

array(['a', '1', '3.14', '(5+2j)'], dtype='<U6')

U6 datatype is a unicode string of 6-character length.  Since we had multiple datatypes, Numpy defaulted to strings so all data could be preserved.  If we remove a, we still can't make everything a float or int because of the complex number

In [17]:
list2 = [1 ,3.14, 5+2j]
np.array(list2) # , dtype=complex)
# np.array(list2).dtype

array([1.  +0.j, 3.14+0.j, 5.  +2.j])

Now let's see what happens when we use floating point numbers and integers

In [18]:
list3 = [1, 5, 3.4, 9.6, 0.9, 5]
np.array(list3) #.dtype

array([1. , 5. , 3.4, 9.6, 0.9, 5. ])

If we check the datatype above, we see it was defaulted to float because it is more precise than integers.  If we want to lose precision and round all numbers down, we can set the dtype=int

In [19]:
np.array(list3, dtype=int)

array([1, 5, 3, 9, 0, 5])

## Limitations Of NumPy Arrays
NumPy Arrays are:
  - Fixed-Length (appending them means making a copy)
  - Fixed-Data Type (only one data type in an array)

Although lists can have multiple datatypes, arrays are more efficient for numerical calculations because they are a single datatype.  We trade versatility for efficiency.

Finally, unlike lists, NumPy arrays can be explicity multidimensional:

In [20]:
np.array([range(i, i + 4) for i in [2, 6, 10]])

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

Input a set of lists inside a larger list to create a 2D array.  The inner lists are treated as rows of the resulting array.

In [21]:
d = np.array([[ 2,  3,  4,  5],[ 6,  7,  8,  9], [10, 11, 12, 13]])
d #.shape is (rows, columns) = (3, 4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## Array Arithmetic: Now Easy!

By default, all operations are performed **Element-Wise**

In [22]:
data = np.array(range(10), dtype=float)
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
data * 2

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [24]:
data * data

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

## Array Arithmetic: Now Fast (on large datasets)!

In [25]:
data = np.array(range(3))
%timeit [el ** 2 for el in data]

1.64 µs ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
%timeit data ** 2

701 ns ± 18.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Arrays Can Be Indexed and Sliced, Just like Tuples and Lists

In [27]:
data = np.array(range(10), dtype=float)
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
data[3]

3.0

In [29]:
data[:5]

array([0., 1., 2., 3., 4.])

## Logical Indexing: Using Bool arrays to filter an array

In [30]:
data = np.array(range(4, 20))
mask = data > 11
dd = data[mask]
np.c_[data,mask] # Translates slice objects to concatenation along the second axis.

array([[ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  1],
       [13,  1],
       [14,  1],
       [15,  1],
       [16,  1],
       [17,  1],
       [18,  1],
       [19,  1]])

In [31]:
dd

array([12, 13, 14, 15, 16, 17, 18, 19])

## Fancy Indexing: Indexing with a list of indices

In [32]:
data[[3, 5, 9]]

array([ 7,  9, 13])

## NumPy comes with Lots of useful math functions!

In [33]:
len(data)

16

In [34]:
np.mean(data)

11.5

In [35]:
np.max(data)

19

In [36]:
np.min(data)

4

In [37]:
np.sum(data)

184

You can see a list of many Numpy functions:
    http://docs.scipy.org/doc/numpy/reference/routines.math.html

## Some Array-Creation Shortcut Functions

There is a numpy extension of the range command.

In [38]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In contrast to the range() command, the arguments to arange can be floating point numbers

In [39]:
a = np.arange(1.4, 10., 0.23); print(a)

[1.4  1.63 1.86 2.09 2.32 2.55 2.78 3.01 3.24 3.47 3.7  3.93 4.16 4.39
 4.62 4.85 5.08 5.31 5.54 5.77 6.   6.23 6.46 6.69 6.92 7.15 7.38 7.61
 7.84 8.07 8.3  8.53 8.76 8.99 9.22 9.45 9.68 9.91]


We created an array filled with a linear sequence starting at 1.4, ending at 10, stepping by 0.23

Linearly spaced samples can be obtained with np.linspace, called as np.linspace(start, stop, number of samples)

In [40]:
b = np.linspace(1.4, 10, 12); print(b)

[ 1.4         2.18181818  2.96363636  3.74545455  4.52727273  5.30909091
  6.09090909  6.87272727  7.65454545  8.43636364  9.21818182 10.        ]


**NOTE:** The difference between np.arange and np.linspace is the last argument, either the step size of the number of samples.  Each one can be useful in different situations!

Numbers on a logarthimic scale can be obtained similarly with np.logspace

In [41]:
c = np.logspace(3, 10, 5); print(c)

[1.00000000e+03 5.62341325e+04 3.16227766e+06 1.77827941e+08
 1.00000000e+10]


We can create arrays of random values from 0 to 1:

In [42]:
np.random.random(5)

array([0.09255266, 0.2150297 , 0.75634041, 0.60840605, 0.14331072])

Or with random integers within a predefined range np.random.randint(start,end,number)

In [43]:
np.random.randint(0,10,(2,10)) # 2 rows  random integers from 0 to 10

array([[7, 9, 0, 9, 1, 0, 6, 1, 3, 0],
       [3, 0, 0, 9, 6, 8, 2, 5, 9, 4]])

You can create arrays of zeros or ones.

In [44]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [45]:
np.ones((7,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

You can create a boolean array by setting the data type parameter

In [46]:
np.ones(4, dtype=bool)

array([ True,  True,  True,  True])

You can create an array of normally distributed random values with a mean of 0 and standard deviation of 2 

In [47]:
np.random.normal(0, 2, (5,5))

array([[ 0.88600035, -0.84628927, -2.90254788, -0.91040047,  1.5150479 ],
       [-1.2888103 , -0.27120169,  2.62734332,  1.21419249, -0.86223007],
       [-5.11672205,  2.91749794, -1.69548488,  1.85733503, -0.0754275 ],
       [-3.57058985, -1.65050369, -0.23793917, -1.73944614,  0.39489052],
       [-2.44385821, -0.77533034, -2.18545219,  3.8236705 , -0.66479869]])

You can create a 3x3 identity matrix

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Getting Indicies and Masking

You can get positions (indices) where elements of two different arrays match using np.where:

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)[0]

array([1, 3, 5, 7])

We could also create a boolean mask based on our equality of interest and use it to index either array

In [50]:
mask = a == b
mask
# a[mask]

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

This type of boolean logical is very powerful and allows you to perform operations on array components that meet a specific criterion by filling in two other options in np.where:

In [51]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

The syntax for np.where is np.where(condition, return if True, return if False)

# Numpy Exercises: Set 1

Extract all odd numbers from arr (answer: array([1, 3, 5, 7, 9]). Can you doing it using a boolean mask and slicing?

In [52]:
arr = np.arange(10)

mask = arr % 2 == 1
arr[mask]
arr[1::2]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [53]:
arr = np.arange(10)

arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Replace all odd numbers in arr with -1 without changing arr (Hint: use np.where)

In [54]:
arr = np.arange(10)

out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Get all items between 5 and 10 from a.  Can you do it in three ways? Use the & operator or np.logial_and() function

In [55]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Method 3
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

Convert a 1D array to a 2D array with 2 rows. (Hint: Read about the np.reshape function with np.reshape?

Solution should look like: array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])

In [56]:
a = np.arange(10)

np.reshape(a,(2,5))
# np.reshape(a,(2,-1)) # Setting -1 automatically decides the number of columns

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Matrices in Numpy

We can also define matrices (two-dimensional tensors)

In [57]:
A = np.array([[1,2],[2,1]], dtype=np.float64)
B = np.array([[5,6],[7,8]], dtype=np.float64)

In [58]:
A = np.array([[1,2],[2,1]])
B = np.array([[5,6],[7,8]])

In [59]:
z = np.zeros((4,4)); print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [60]:
o = np.ones((2,5)); print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


We could create the same matrix using the reshape function if we wanted to.

In [61]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

A numpy array has a set of properties that we can query:

In [62]:
A.ndim

2

In [63]:
A.shape

(2, 2)

In [64]:
A.size

4

In [65]:
A.dtype

dtype('int64')

# Combining arrays and matrices

Concatenation allows you to take two or more arrays of the same shape and merge them together

In [66]:
a1 = np.arange(9).reshape((3,3))
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
a2 = np.arange(10,19).reshape((3,3))
a2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
np.concatenate((a1, a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

By default, concatenation happens on axis = 0, or along the rows, but we can set it to columns:

In [69]:
np.concatenate((a1, a2), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

There are two other useful functions that stack vertically (vstack) or horizontally (hstack):

In [70]:
np.vstack((a1, a2, a1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [71]:
np.hstack((a2, a1, a2))

array([[10, 11, 12,  0,  1,  2, 10, 11, 12],
       [13, 14, 15,  3,  4,  5, 13, 14, 15],
       [16, 17, 18,  6,  7,  8, 16, 17, 18]])

Swapping columns can be done with slice methods.  Here we swap the first and second columns:

In [72]:
q = np.arange(9).reshape(3,3)
q
# q[:, [1, 0, 2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Now we can perform mathematical operations on matrices A and B

In [73]:
print(A); print("\n"); print(B)

[[1 2]
 [2 1]]


[[5 6]
 [7 8]]


In [74]:
print(A+B)

[[6 8]
 [9 9]]


In [75]:
print(np.add(A,B))

[[6 8]
 [9 9]]


In [76]:
print(A*B)

[[ 5 12]
 [14  8]]


In [77]:
print(np.dot(A,B))

[[19 22]
 [17 20]]


# The zip() function

Python's zip() function takes in a iterables as arguments and returns an **iterator**.  The iterator generates a series of tuples containing elements from each iterable.  It accepts iterables of multiple types, including files, lists, tuples, arrays, etc.

The zip() function becomes very powerful when using it to iterate over multiple arrays, especially when used in combination with enumerate().

In [78]:
a3 = np.arange(1,10)
a4 = np.arange(11,20)
for i3, i4 in zip(a3,a4):
    print(i3,i4)

1 11
2 12
3 13
4 14
5 15
6 16
7 17
8 18
9 19


enumerate() provides an index for all of the elements that are looped (iterated) over.

In [79]:
for i, (i3, i4) in enumerate(zip(a3,a4)):
    print(i, i3,i4)

0 1 11
1 2 12
2 3 13
3 4 14
4 5 15
5 6 16
6 7 17
7 8 18
8 9 19


# Numpy Exercises: Set 2

Create the following pattern from the basic array a = np.array([1,2,3]) without hardcoding to create this solution:

    array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**Hint:** You need to use the functions np.tile() and np.repeat()

In [80]:
a = np.array([1,2,3])

np.concatenate( (np.repeat(a,3), np.tile(a,3)) )

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Get the common items between a and b using the np.intersect1d() function

In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

Find the unique values contained in a but not b.  Can you do it two different ways using either np.setdiff1d() or np.in1d()?

In [82]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# a[~np.in1d(a,b)]
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Swap the second and third rows of this matrix

In [83]:
w = np.arange(9).reshape(3,3)

w[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

The function maxx accepts two scalars and returns the maximum value.  Write a new function called pair_max() that accepts two arrays and returns as array containing the elementwise max value.

**HINT:** Use the zip() function!

In [84]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [3]:
import numpy as np

In [4]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def pair_max(x, y):
    z=[]
    for xi, yi in zip(x,y):
        if xi >= yi:
            z.append(xi)
        else:
            z.append(yi)
    return np.array(z, dtype=float)

pair_max(a, b)
#Solution: array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

# Matrix Equations

As an example, take 

$$ A = \begin{pmatrix} 1 & 2 \\2 & 1 \end{pmatrix}$$

and

$$ {\bf x} = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}$$

so that 

$$ A {\bf x} =\begin{pmatrix} 1 & 2 \\2 & 1 \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}= \begin{pmatrix} x_1 + 2 x_2\\ 2 x_1 + x_2 \end{pmatrix}$$

We can now solve: $$ A {\bf x} = {\bf b}$$

for instance, $$ \begin{pmatrix} x_1 + 2 x_2\\ 2 x_1 + x_2 \end{pmatrix} = \begin{pmatrix}2\\1\end{pmatrix}$$

In Python, we do this using the linear algebra sub-module linalg.

In [86]:
A = np.array([[1, 2], [2, 1]])

In [87]:
print(A)

[[1 2]
 [2 1]]


In [88]:
np.linalg.solve(A,np.array([2,1]))

array([0., 1.])

We can do this explicitly, step-by-step, by first forming the inverse of $A$.

In [89]:
np.linalg.inv(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [90]:
b = np.array([2,1])

And now we take $$ A^{-1} {\bf b}$$

In [91]:
np.dot(np.linalg.inv(A),b)

array([0., 1.])

<h3>Eigenvalue equation:</h3> $$ A {\bf v} = \lambda {\bf v}$$

where $A$ is a square matrix, ${\bf v}$ a vector, and $\lambda$ a scalar value (possibly complex-valued)

If we align all the vectors ${\bf v}$ that satisfy the eigenvalue equation as column vectors in a new matrix $V$, then

$$
A V = V  
  \begin{pmatrix}
    \lambda_{1} & 0 & 0\\
    0 & \ddots & 0  \\
    0 &  0 & \lambda_{n}
  \end{pmatrix}
$$

where we have a diagonal matrix 
$$
\Lambda= \begin{pmatrix}
    \lambda_{1} & 0  & 0 \\
    0 & \ddots & 0  \\
    0 &  0 & \lambda_{n}
  \end{pmatrix}
$$

We can now multiply by $V^{-1}$ from the left

$$V^{-1} A V= \Lambda$$

This is called diagonalizing a matrix. 

In [92]:
evals, evecs = np.linalg.eig(A)

In [93]:
print(evals)

[ 3. -1.]


The eigenvectors are the columns of the following matrix

In [94]:
print(evecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [95]:
print(B)

[[5 6]
 [7 8]]


Indexing of a matrix should be done as matrix[rows, columns]

In [96]:
B[:,0] # Gives us all rows, first column

array([5, 7])

In [97]:
B[1,:] # Gives us second row, all columns

array([7, 8])

We need to address the first eigenvector as follows

In [98]:
evecs[:,0]

array([0.70710678, 0.70710678])

and not as 

In [99]:
evecs[0]

array([ 0.70710678, -0.70710678])

which refers to the <b>first</b> row, not the first column of the eigenvector matrix. 

Let us show that the computed vectors and values satisfy the eigenvalue equation: $$ A {\bf v} = \lambda {\bf v}$$

In [100]:
evecs[:,1]

array([-0.70710678,  0.70710678])

In [101]:
np.dot(A, evecs[:,1])/evals[1] 

array([-0.70710678,  0.70710678])

In [102]:
np.dot(A, evecs[:,1]) - evals[1] * evecs[:,1]

array([7.77156117e-16, 1.11022302e-16])

The function np.allclose() is used to find if two arrays are element-wise equal within a very small tolerance

In [103]:
np.allclose(np.dot(A, evecs[:,1]), evals[1] *evecs[:,1])

True

In [104]:
np.allclose(np.dot(A, evecs[:,1]), np.array([1,2]))

False

This final part demonstrates one practical use of numpy.  Principal Component Analysis could be performed by finding eigenvectors and eigenvalues of matrices, which is one analysis that is common in data analysis of all types.